### PR TITLE
Add tutorial field in config.json files

### PR DESCRIPTION
**Pull request by LuisFerTR**
# Pull Request

Signed-off-by: Luis Talavera <luisfertalavera15@gmail.com>

## What I did
Add new `tutorial field` in config.json files
## How I did it
After read documentation, I added `tutorial field` and its respective value in config.json files
## What kind of change does this PR make

- [ ] Major
- [x] Minor
- [ ] Patch

## Description for the changelog

Make the existing formulas compatible by adding the tutorial field in the inputs.

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]

**Comment by GuillaumeFalourd** [comment]
Thank you again for contributing @LuisFerTR  👍

We are still working on the form for the Zup IT Challenge (https://insights.zup.com.br/hacktoberfest) and we'll send it to you as soon as it will be validated.

**Comment by LuisFerTR** [comment]
I like contribute, I'm learning a lot, and about the challenge I'm from México, is it a problem?

**Comment by GuillaumeFalourd** [comment]
Unfortunately, the Zup IT Challenge will only work for Brazilians, this year @LuisFerTR :(
I hope we'll expand to other countries (like the Digital Ocean does) in the future.

**Comment by LuisFerTR** [comment]
There's no problem @GuillaumeFalourd, it's a pleasure to help, I also hope you'll expand in the future. 
Thank so you much for the experience :smile:

**Pull request merged**
