### PR TITLE
Edit coffe-go formula README

### PR DESCRIPTION
**Pull request by LuisFerTR**
# Pull Request

## What I did
I added how to execute coffee-go formula in prompt, by stdin, with docker and by stdin with docker, I also added a little gif as an example of its execution
## How I did it
Reading documentation I figured it out how to execute it by stdin, recorded my screen to generate the example of its execution gif.
## What kind of change does this PR make

- [ ] Major
- [x] Minor
- [ ] Patch

## Description for the changelog

RIT DEMO COFFEE-GO formula have a complete README file explaining what the formula does, with an example of its execution (GIF).

### CODE REVIEW

**Review by GuillaumeFalourd — APPROVED** [review]

**Comment by LuisFerTR** [comment]
Excuse me, what's missing to merge the branch?

**Comment by GuillaumeFalourd** [comment]
Hi @LuisFerTR  , thank you for your contribution 👍

I'm just validating with our team how to add the DCO (Developer Certificate of Origin) configuration to this repository before merging it, as I was just informed that it's a premisse to participate to our company challenge as well (https://insights.zup.com.br/hacktoberfest).

I'll let you know as soon it will be resolved.

**Comment by GuillaumeFalourd** [comment]
@LuisFerTR , we just added the DCO configuration for this repository.
As it didn't trigger anything on the PR, I believe you'll have to close and open this PR again.
Is it be possible ?

**Comment by LuisFerTR** [comment]
Of course, there's no problem

**Pull request closed without merging**
