### PR TITLE
Challenges

### PR DESCRIPTION
**Pull request by carloskotacho**
# Pull Request

## What I did

[Challenge 1 - Inputs](https://docs.ritchiecli.io/v/v2.0-pt/challenges/level-1)
[Challenge 2 - Credentials](https://docs.ritchiecli.io/v/v2.0-pt/challenges/level-2)
[Challenge 3 - Conditional entries](https://docs.ritchiecli.io/v/v2.0-pt/challenges/level-3)
[Challenge 4 - Encapsulation](https://docs.ritchiecli.io/v/v2.0-pt/challenges/level-4)

## How I did it

Created following documents of [Ritchie](https://docs.ritchiecli.io/v/v2.0-pt/)

## How to verify it

**Challenge 1 - Inputs**
- `rit build formula`
- `rit math sum numbers`

**Challenge 2 - Credentials**
- `rit build formula`
- `rit github get user`

**Challenge 3 - Conditional entries**
- `rit build formula`
- `rit get tools`

**Challenge 4 - Encapsulation**
- `rit build formula`
- `rit math calculate`

## What kind of change does this PR make

- [ ] Major
- [x] Minor
- [ ] Patch

### CODE REVIEW

**Comment by GuillaumeFalourd** [comment]
Hi @carloskotacho , and thank you for your contribution 🙂

I'm actually wondering if the ritchie-formulas-demo repository is the best place to add formulas from the challenge section of our documentation.

What would you think about creating a ritchie-formulas-challenges repository, with the challenges solutions for each language, with the language used for each formula added on the command to make it clearer on the repository structure.

rit node math sum numbers
rit python math sum numbers
rit java math sum numbers
...

I believe it would be helpful and we could even add a link to this repo on the official documentation 😁

**Comment by carloskotacho** [comment]
Perfect @GuillaumeFalourd ! :grinning:

**Comment by GuillaumeFalourd** [comment]
Is it this one @carloskotacho : https://github.com/carloskotacho/ritchie-formulas-local ? 😄

**Comment by carloskotacho** [comment]
@GuillaumeFalourd https://github.com/carloskotacho/ritchie-formulas-challenges

**Comment by GuillaumeFalourd** [comment]
Thank you for contributing @carloskotacho  👍 

We want to show our appreciation by sending you some swag. Could you please fill out [this form](https://zup1.typeform.com/to/zrOF5cpp) so we can send it to you? 🚀

**Comment by carloskotacho** [comment]
Please :smile:

image

**Comment by GuillaumeFalourd** [comment]
You can add this link twice: https://github.com/ZupIT/ritchie-formulas-demo/pull/28 😺

**Comment by carloskotacho** [comment]
It worked! thanks :smile:

**Pull request closed without merging**
